Repository alexalbu98/Crawler, pull requests merged in 2020-12, with the labels that each got.

#5 Adaugare fisier SDD
  SDD.docx
Labels: documentation

#4 Elaborare SRS
  SRS.docx
Labels: documentation

#7 Aduagarea Tamplate
  .gitignore
  Crawler.iml
  src/com/mta/Main.java
Labels: enhancement

#18 Update pentru structura proiectului
  src/mta/main/Main.java
Labels: bug

#19 Creare singletons
  src/mta/Singletons/AllowedFilesList.java
  src/mta/Singletons/ParentsList.java
  src/mta/Singletons/TaskQueue.java
  src/mta/Singletons/VisitedPageList.java
  src/mta/Templates/Tuple.java
  src/mta/main/Main.java
Labels: enhancement

#23 Creare Metoda de verificare argumente.
  src/mta/AbstractClasses/Task.java
  src/mta/Classes/Crawler.java
  src/mta/Exceptions/ArgumentNotSupportedException.java
  src/mta/Exceptions/SitesFileNotSpecifiedException.java
  src/mta/Exceptions/SizeNotSpecifiedException.java
  src/mta/Singletons/TaskQueue.java
  src/mta/main/Main.java
Labels: enhancement

#39 Creare metoda de citire si gasire a linkurilor dintr-un fisier
  src/mta/Classes/CrawlTask.java
  src/mta/Classes/Crawler.java
  src/mta/Singletons/ThreadPool.java
Labels: enhancement

#40 Creare clasa SearchWordsTask
  Crawler.iml
  Download/mta.html
  Download/test.txt
  Download/wp-content/plugins/bdthemes-element-pack-lite/assets/css/bdt-uikit.css
  Download/wp-content/plugins/bdthemes-element-pack-lite/assets/css/element-pack-site.css
  Download/wp-content/testing/another_test/file.txt
  Download/wp-content/testing/another_test/mure.txt
  Download/wp-content/themes/HighendWP/styles.css
  Download/wp-content/uploads/Mihai-Togan_Lista-lucrari-min.pdf
  searched_words.txt
  src/mta/Classes/Crawler.java
  src/mta/Classes/SearchWordsTask.java
  src/mta/Singletons/SearchWordsList.java
  src/mta/Singletons/TaskFactory.java
  src/mta/main/Main.java
Labels: enhancement
